### PR TITLE
Rename License.txt to LICENSE.txt

### PR DESCRIPTION
**Pull request by sometimesfood**
This pull request renames `License.txt` to `LICENSE.txt` so the license is included in the module zip file.

Apparently, the golang team does not intend to change what files are included in the zip file:
https://github.com/golang/go/issues/43817#issuecomment-764854847

### CODE REVIEW

**Comment by billziss-gh** [comment]
@sometimesfood I am unclear on the reasons for renaming the license. Can you please explain the rationale?

**Comment by sometimesfood** [comment]
Sorry for the noise, my mistake. I completely misunderstood the comment linked above.

When importing and vendoring cgofuse, the license file is not included in the vendor directory. I thought that this was due to the file name of the license file, but I just noticed that the license is only contained in the project root, not in the `fuse` directory. My bad.

When importing cgofuse using `go mod vendor`, it would be great to have a copy of the license in the vendor directory. Would you be open to having another copy of the license in the `fuse` directory or maybe symlinking it so that the license is distributed with the code when using `go mod vendor`?

**Comment by sometimesfood** [comment]
Sorry for the confusion, I should have done so earlier.

When importing cgofuse and using `go mod vendor`, the license file is not distributed with the code because it is not included in the module zip file. This seems to be due to the file name of the license file.

If I import the package `github.com/billziss-gh/cgofuse/fuse` and use `go mod vendor` to download a copy of the sources to my `vendor` directory, the directory `vendor/github.com/billziss-gh/cgofuse/` does not contain a copy of the license file.

For comparison: If I import `github.com/hashicorp/golang-lru/simplelru`, the directory `ls vendor/github.com/hashicorp/golang-lru/` contains a copy of the `LICENSE` file.

I am not sure, why that is, but the golang repo comment linked above indicates it might be due to the file name of the license file in your repo.

**Comment by sometimesfood** [comment]
Btw, just to be clear: Renaming the license file, adding a new version tag and importing the resulting version from a private repo works just as expected – the license file is included correctly in the module zip file.

**Comment by billziss-gh** [comment]
Thank you for the explanation. I will merge this in.

**Comment by sometimesfood** [comment]
Great, thanks!

**Pull request merged**
